config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get 'api/usernames'
  resources :wikis 
  resources :charges
  resources :users, only: [:show, :index, :create] do 
   get '/shared' => 'users#shared', as: :shared
  end 
  resources :collaborators

  root to: 'welcome#index'

  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  validates :user_id, 
            :presence => {:message => "does not exist."},
            :uniqueness => {:scope => :wiki_id, :message => "already is a collaborator." }

  validates :wiki_id, 
            :presence => {:message => "does not exist."}

  

  #defining getter method for the attribute created
  def user_name
    if self.user
      self.user.user_name
    end
  end

  #setter method syntax for the attribute created
  def user_name=(value)
    if user = User.where(:user_name => value).first
      self.user_id = user.id
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :collaborators
  has_many :wikis, through: :collaborators

  has_many :created_wikis, class_name: "Wiki"
  
  def has_authority_to_delete_collaborators?
    raise
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators 
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  after_create :add_creator_as_collaborator

  def editable_by?(user)
    user.paid || self.creator.user_name == user.user_name
  end

  def deletable_by?(user)
    self.creator.user_name == user.user_name
  end

  def accessible_by_current_user(user)
    if self.public
      true
    else
      if user == nil
        false
      else
        if Collaborator.where(wiki_id: self.id, user_id: user.id).count > 0
          true
        else
          false 
        end
      end
    end
  end

  def age
    time_ago_in_words(self.created_at)
  end

  def author
    self.creator.user_name
  end

  def public_status
    self.public ? "Public" : "Non-public"
  end

  def short_description
    "submitted #{self.age} ago by #{self.author}, #{self.public_status} Wiki"
  end

  private

 def add_creator_as_collaborator
   self.creator.collaborators.create(wiki: self)
 end 

end

app/controllers/api_controller.rb
class ApiController < ApplicationController


  def usernames
    render json: User.where("id != #{current_user.id}").pluck(:user_name) 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :user_name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500
     
    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
      )
     
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
      )
    
    # change user status to paying user
    current_user.update_attribute(:paid, true)
    flash[:notice] = "You are now in the Wiki Private Club!"
    $user = User.find(current_user.id)
    redirect_to $user  

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
   @collaborator = Collaborator.new(post_params)
   if @collaborator.save
      flash[:notice] = "Collaborator added"
      redirect_to edit_wiki_path(@collaborator.wiki)
   else
#     binding.pry
     flash[:error] = ""
     @collaborator.errors.full_messages.each do |msg|
       flash[:error] += msg
     end
     redirect_to edit_wiki_path(@collaborator.wiki)
   end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki
    if @wiki.deletable_by?(current_user)
      if @collaborator.destroy
        flash[:notice] = "You have removed #{@collaborator.user.user_name} as a collaborator from this Wiki" 
        redirect_to edit_wiki_path(@collaborator.wiki) 
      else
        flash[:error] = "There was an error. Please try again"
        redirect_to edit_wiki_path(@collaborator.wiki)
      end
    else 
      flash[:error] = "Only the owner may delete collaborators."
      redirect_to edit_wiki_path(@collaborator.wiki)
    end
  end

  private

  def post_params
    params.require(:collaborator).permit(:wiki_id, :user_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js

  def index
  end

  def show
    @title = "My Wikis"
    @wikis = current_user.created_wikis
    @new_wiki = Wiki.new
  end

  def shared
    @title = "Wikis Shared with Me" 
    @wikis = current_user.wikis.where.not(user_id: current_user.id)
    @new_wiki = Wiki.new
    render :show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  respond_to :html, :js

  def index
    #pulling most recent public wikis and displaying titles
    @wikis = Wiki.where(public: true)
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  respond_to :html, :js

  def index
    @wikis = Wiki.where(public: true)
  end

  def show
    @wiki = Wiki.find(params[:id])
    if @wiki.accessible_by_current_user(current_user)
      @wiki
    else
      redirect_to "/"
    end
  end

  def new
  end

  def create
    @wiki = Wiki.new(post_params)
    @wiki.user_id = current_user.id
    @user = User.find(@wiki.user_id)
    if @wiki.save
      flash[:notice] = "Your new Wiki has been created."
      redirect_to @user
    else
      flash[:error] = "There was an error in creating your Wiki. Please start over."
      redirect_to @user
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    if @wiki.accessible_by_current_user(current_user)
      @collaborator = Collaborator.new(:wiki_id => @wiki.id)
    else
      redirect_to '/'
    end
  end

  def update
    @wiki = current_user.wikis.find(params[:id])
    @user = User.find(@wiki.user_id)
    if @wiki.update_attributes(post_params)
      flash[:notice] = "You have updated a Wiki"
      redirect_to @user
    else
      flash[:error] = "There was an error encountered. Please try again."
      redirect_to @user
    end
  end

  def destroy
    @wiki = current_user.wikis.find(params[:id])
    @user = User.find(@wiki.user_id)
    if @wiki.destroy
      flash[:notice] = "You have deleted Wiki '#{@wiki.title}'."
      redirect_to @user
    else
      flash[:error] = "There was an error in the process. Please try it again."
      redirect_to @user
    end
  end

  private

  def post_params
    params.require(:wiki).permit(:title, :body, :public)
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>You are not a paid user. You may now create Private Wikis.</h1>
<h4>Thanks, you paid <strong>$5.00</strong>!</h4>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
  <h3> To be able to edit shared Wikis or be able to create private Wikis and share them you must be a paying user!</h3>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
     data-description="Show me the $$"
    data-amount="500"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasWiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Saas Home", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <% if current_user %>
         <% if !current_user.paid %>
           <li><%= link_to "Private Wikis", new_charge_path %></li>
         <% end %>
      <% end %>
      <% if current_user %>
        <li><%= link_to "My Wikis", current_user %></li>
        <li><%= link_to "Wikis Shared With Me", user_shared_path(current_user) %></li>
      <% end %>
      <div class="pull-right user-info">
        <% if current_user %>
          <%= current_user.email %> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %> 
        <% end %>
      </div>
    </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div> 
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div> 
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div> 
    <% end %>

    <%= yield %>

  </div><!--end of container-->
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="modal fade" id="createWiki">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for @new_wiki do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create New Wiki</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title%>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, cols: 42 %>
        </div>
        <% if current_user.paid %> 
          <div class="form-group">
            <%= f.label :public %>
            <%= f.check_box :public %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%=f.submit "Create Wiki", class: "btn btn-primary" %>
      </div>
        <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<h1><%= @title %></h1>
<div class="row">
  <div class="col-md-8">
    <%= render partial: "wikis/wikis", collection: @wikis %>
  </div>
  
  <div class="col-md-4">
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#createWiki">
      Create a new Wiki
    </button>
  </div><!-- end of col -->
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<div class="row">
  <div class="col-md-8">
    <ul class="list-group">
      <% @wikis.each do |wiki| %>
        <li class="list-group-item">
          <%= link_to  wiki.title, wiki %>
          <small>
            submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.creator.user_name %> 
          </small>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/wikis/_wikis.erb
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= wikis.title %>
        </h3>
      </div>
      <div class="panel-body">
        <%= wikis.body %>
      </div>
      <div class="panel-footer">
        <%= wikis.short_description %>
        <% if wikis.editable_by?(current_user) %>
          <%= link_to "Edit", edit_wiki_path(wikis), class: 'btn btn-success' %> 
          <% if wikis.deletable_by?(current_user) %>
            <%= link_to "Delete Wiki", wikis, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'Do you want to delete this Wiki?' } %>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/wikis/edit.html.erb
<h1>Edit <%= @wiki.title %> Wiki</h1>
<h4><%= @wiki.public ? "Public" : "Non-public" %></h4>
<div class="row">

  <div class="col-md-4">
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title%>
    </div>
    
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, cols: 42 %>
    </div>
    <% if @wiki.deletable_by?(current_user) %>    
      <div class="form-group">
        <%= f.label :public %>
        <%= f.check_box :public %>
      </div>
    <% end %>
    <div class="form-group">
      <%=f.submit "Update Wiki", class: "btn btn-primary" %>
    </div>
  <% end %>
  </div><!--end of wiki panel-->

  <div class= "col-md-2 col-md-offset-1">
    <h3>Collaborators</h3>
    <% @wiki.collaborators.each do |collaborator| %>
      <% if (collaborator.user_name != current_user.user_name) %>
        <p><%= link_to check_box_tag(:collaborator), collaborator, method: :delete %> <%= collaborator.user_name %></p>
      <% end %>
    <% end %>
  </div>

    <% if current_user.paid %>    

  <div class="col-md-4 col-md-offset-1">
    <h3>Add collaborators to this Wiki</h3>
    <%= form_for @collaborator do |f| %>
        <%= f.hidden_field :wiki_id %>
        <div id="the-basics" class="form-group">
          <%= f.text_field :user_name, class: "typeahead", placeholder: "Collaborator" %>
        </div>
        <div class="form-group">
          <%= f.submit "Add", class: "btn btn-success" %>
        </div>
    <% end %>
  </div>

    <% end %>
</div>

app/views/wikis/index.html.erb
<h1>Here are all our Public Wikis</h1>
<% @wikis.each do |wiki| %>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= wiki.title %>
        </h3>
      </div>
      <div class="panel-body">
        <%= wiki.body %>
      </div>
      <div class="panel-footer">
        submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%=  wiki.creator.user_name %>     
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/wikis/new.html.erb
<h1>Wikis#new</h1>
<p>Find me in app/views/wikis/new.html.erb</p>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= @wiki.title %>
        </h3>
      </div>
      <div class="panel-body">
        <%= @wiki.body %>
      </div>
      <div class="panel-footer">
        submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.creator.user_name %>
      </div>
    </div>
  </div>
</div>